# Generated by Django 3.1.5 on 2021-01-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('caption', models.TextField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
